services:
  database:
          build:
            context: ./Database
            dockerfile: Dockerfile
          container-name: my-mysql-db
          enviornment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: studentapp 
          ports:
            - "3306:3306"
          networks:
            - app-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container-name: backend-service
    enviornment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: studentapp
      DB_USER: root
      DB_PASSWORD: 123
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network      

